name: HexaEcon
version: '1.0'
main: space.kiyoshi.hexaecon.HexaEcon
author: TheBloodyAxolotl
website: https://discord.kiyoshi.space
api-version: 1.16
softdepend:
  - PlaceholderAPI
commands:
  eco:
    description: "With this command u can see ur balance or the balance of other players"
    aliases: [ "balance", "bal" ]
  wallet:
    description: "Main HexaEcon Command"
    aliases: [ "money", "coin", "coins", "econ", "economy", "bank" ]
  pay:
    description: "With this command you can send money to your friends"
    aliases: [ "sendmoney", "payment" ]
  baltop:
    description: "With this command you can get a balance top"
    aliases: [ "balancetop", "topbalance"]